theme: jekyll-theme-cayman
title: Environment lookup
description: Interactive and programmable environment control
markdown: CommonMarkGhPages

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
