exclude:
  - .github
  - command
  - config
  - neighbor
  - search
  - .gitattributes
  - .gitignore
  - go.mod
  - go.sum
  - main.go
  - README.md
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

