name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  push_to_gh-pages_branch:
    name: "Push to gh-pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add custom layout
        env:
          CONFIG: |
            exclude:
              - .github
              - command
              - config
              - neighbor
              - search
              - .gitattributes
              - .gitignore
              - go.mod
              - go.sum
              - main.go
              - README.md
            markdown: CommonMarkGhPages
            commonmark:
              options: ["SMART", "FOOTNOTES"]
              extensions: ["strikethrough", "autolink", "table", "tagfilter"]

          LAYOUT_DEFAULT: |
            <!DOCTYPE html>
            <html lang="en-US">
            <head>
                <meta charset="UTF-8">
                <meta name="go-import" content="janmarten.name/env git https://github.com/johmanx10/env">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta name="theme-color" content="#157878">
                <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
                <link rel="stylesheet" href="https://pages-themes.github.io/cayman/assets/css/style.css?v=d4cdac15d273c45cb6d9a0b1d2772a21008ea063">
            </head>
            <body>
            <header class="page-header" role="banner">
                <h1 class="project-name">Environment lookup</h1>
                <h2 class="project-tagline">Interactive and programmable environment control</h2>
            </header>

            <main id="content" class="main-content" role="main">
                {{ content }}
            </main>
            </body>
            </html>
        run: |
          mkdir _layouts && echo "$LAYOUT_DEFAULT" > _layouts/default.html
          echo "$CONFIG" > _config.yml
      - uses: EndBug/add-and-commit@v4
        with:
          add: .
          author_name: Jan-Marten de Boer
          author_email: github@johmanx.com
          force: true
          message: Add custom layout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes to Github Pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
